apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-msa
spec:
  # 운영 환경은 트래픽이 많으므로 3개의 파드로 배포합니다.
  replicas: 3
  template:
    spec:
      containers:
      - name: hello-msa
        image: ghcr.io/bitmool/k8s-gitops-practice/hello-msa:latest
        ports:
        - containerPort: 3000
        env:
        - name: ENV_NAME
          value: "Production 🔥"
