name: CI Pipeline (Docker Build & Push)

# 언제 이 파이프라인 로봇이 깨어날지 (트리거 조건)
on:
  push:
    paths:
      - 'apps/hello-msa/**'  # 이 폴더 안의 파일이 수정되었을 때만 작동!

env:
  REGISTRY: ghcr.io
  # github.repository는 자동으로 "본인아이디/저장소명"을 가리킵니다.
  IMAGE_NAME: ${{ github.repository }}/hello-msa

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest  # 깃허브가 무료로 빌려주는 리눅스 서버 환경

    permissions:
      contents: read
      packages: write       # GHCR(패키지 레지스트리)에 이미지를 쓸 수 있는 권한 부여

    steps:
      # 1단계: 깃허브 서버로 내 소스 코드를 다운받아 옴
      - name: Checkout repository
        uses: actions/checkout@v6

      # 2단계: GHCR(도커 레지스트리)에 로그인
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # 깃허브가 자동으로 발급해주는 마스터 키

      # 3단계: Docker 이미지 굽고(Build) GHCR로 올리기(Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./apps/hello-msa
          push: true
          # git commit의 고유 해시값과 latest 태그를 동시에 부착
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
